# -*- coding: utf-8 -*-
"""01_Zero_Shot_Prompting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3pNZNlbfPwoyz0kHaShwo1u5aaArp02

# 🎯 Zero-Shot Prompting

**Day 2 — Notebook 1 of 5 | Estimated Time: 20 minutes**

---

## What You'll Learn
- What zero-shot prompting is and when to use it
- How to write clear, direct instructions
- Common zero-shot tasks: classification, extraction, summarization, translation

---

## What is Zero-Shot Prompting?

**Zero-shot** means you give the model a task **without any examples**. You simply describe what you want, and the model uses its pre-trained knowledge to complete it.

This is the simplest form of prompting and works well for:
- Straightforward tasks the model already knows how to do
- When you don't have example data to provide
- Quick prototyping and exploration

## Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U -q "google-genai>=1.0.0"

!pip install google-auth==2.47.0

import sys, os
import time

import json
import re
from google import genai
from google.genai import types
from IPython.display import Markdown


try:
    from google.colab import auth
    auth.authenticate_user()
    print("✅ Authenticated via Colab")
except ImportError:
    print("✅ Using local credentials (gcloud auth)")


client = genai.Client(
    vertexai=True,
    project="chanakya-476010",
    location="us-central1",
)
MODEL_ID = "gemini-2.5-flash"
print("✅ Ready!")

"""---

## 1. Classification

Ask the model to classify text into categories — no examples needed.
"""

# Sentiment classification
prompt = """
Classify the sentiment of this review as Positive, Negative, or Neutral:

"I go to this restaurant every week, I love it so much."
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
print(f"Sentiment: {response.text.strip()}")

# Topic classification
prompt = """
Classify the following news headline into one of these categories:
Technology, Sports, Politics, Entertainment, Science

Headline: "NASA's James Webb Space Telescope captures stunning images of distant galaxies"
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
print(f"Category: {response.text.strip()}")

"""---

## 2. Information Extraction

Extract specific information from unstructured text.
"""

# Extract entities
prompt = """
Extract all person names, organizations, and locations from this text:

"Sundar Pichai, CEO of Google, announced a new AI research partnership
with Stanford University during a conference in San Francisco."
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

# Extract structured data
prompt = """
Extract the following details from this job posting:
- Job Title
- Company
- Location
- Required Experience

Job Posting: "We at TechCorp are looking for a Senior Data Scientist
in our Bangalore office. Candidates must have 5+ years of experience
in machine learning and Python."
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

"""---

## 3. Summarization

Condense long text into shorter summaries.
"""

prompt = """
Summarize the following text in 2 sentences:

"Artificial intelligence has been transforming numerous industries, from healthcare
to finance, manufacturing to entertainment. In healthcare, AI is being used for
drug discovery, medical imaging analysis, and patient diagnosis support. Financial
institutions use AI for fraud detection, algorithmic trading, and risk assessment.
The manufacturing sector has embraced AI for quality control, predictive maintenance,
and supply chain optimization. Meanwhile, the entertainment industry uses AI for
content recommendation, game development, and special effects creation."
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

"""---

## 4. Translation & Transformation

Convert text between languages, formats, or styles.
"""

# Translation
prompt = """
Translate the following English text to French, Spanish, and Japanese:

"The weather is beautiful today. Let's go for a walk in the park."
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

# Code explanation
prompt = """
Explain what this Python code does in plain English:

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

"""---

## 5. Tips for Better Zero-Shot Prompts

| Tip | Bad Example | Good Example |
|-----|-----------|-------------|
| **Be specific** | "Tell me about dogs" | "List 5 popular dog breeds for families with children" |
| **Specify format** | "Summarize this" | "Summarize this in 3 bullet points" |
| **Set constraints** | "Write about AI" | "Write a 100-word explanation of AI for beginners" |
| **Define the task** | "Fix this" | "Find and fix the syntax error in this Python code" |

---

## 🏋️ Exercise 1: Classification Challenge

Write zero-shot prompts to classify the following customer support messages into categories: `Billing`, `Technical`, `General Inquiry`, or `Complaint`.
"""

# Exercise 1: Classify customer support messages

messages = [
    "I was charged twice for my subscription last month.",
    "How do I reset my password?",
    "Your product is terrible and I want a full refund!",
    "What payment methods do you accept?",
    "The app keeps crashing when I try to upload a file.",
]

for msg in messages:
    # TODO: Write a prompt that classifies the message
    prompt = f"""Classify the prompts into meaningful buckets like Billing, Technical, General Inquiry, or Complaint.

    "{msg}"
    """

    response = client.models.generate_content(model=MODEL_ID, contents=prompt)
    print(f"Message: {msg}")
    print(f"Category: {response.text.strip()}")
    print()

"""---

## 🏋️ Exercise 2: Email Extractor

Write a zero-shot prompt that extracts the sender, recipient, subject, urgency level, and key action items from an email.
"""

# Exercise 2: Email information extraction

email = """
From: sarah.chen@company.com
To: dev-team@company.com
Subject: URGENT - Production database migration this Friday

Hi team,

This is a reminder that we have a critical database migration scheduled
for this Friday at 10 PM EST. Please ensure all pending PRs are merged
by Thursday EOD. The migration window is 4 hours, and we need at least
two engineers on-call during this time.

Action items:
1. Merge all pending PRs by Thursday
2. Confirm your on-call availability
3. Run the pre-migration checklist

Thanks,
Sarah
"""

# TODO: Write a prompt that extracts structured info from this email
prompt = f"""GIve me a structured format of the main details like sender,receipient , issue , time , Action items in a json format which
then will be needed for an MoM. Have no more than 3 important details per field
{email}
"""

response = client.models.generate_content(model=MODEL_ID, contents=prompt)
Markdown(response.text)

"""---

## 📚 Further Reading

| Resource | Type | Link |
|----------|------|------|
| Zero-Shot Prompting Guide | Blog | [promptingguide.ai/techniques/zeroshot](https://www.promptingguide.ai/techniques/zeroshot) |
| Google Gemini Prompting Strategies | Docs | [ai.google.dev/gemini-api/docs/prompting-strategies](https://ai.google.dev/gemini-api/docs/prompting-strategies) |

---

**Next up:** [02_Few_Shot_Prompting.ipynb](./02_Few_Shot_Prompting.ipynb) — Teach the model by providing examples
"""